export const equipments = [
  {
    id: 1,
    name: "swiss ball",
    title: "Swiss Ball",
    image: require("../assets/ferioLabs/swissball.png"),
    pressed: false,
  },
  {
    id: 2,
    name: "barbell",
    title: "Barbell",
    image: require("../assets/ferioLabs/barbell.png"),
    pressed: false,
  },
  {
    id: 3,
    name: "jump rope",
    title: "Jump Rope",
    image: require("../assets/ferioLabs/rope.png"),
    pressed: false,
  },
  {
    id: 4,
    name: "dumbells",
    title: "Dumbell",
    image: require("../assets/ferioLabs/dumbells.png"),
    pressed: false,
  },
  {
    id: 5,
    name: "abdonimal bench",
    title: "Abdominal Bench",
    image: require("../assets/ferioLabs/abdominalbench.png"),
  },
  {
    id: 6,
    name: "leg /extension curl machine",
    title: "Leg /Extension Curl Machine",
    image: require("../assets/ferioLabs/curlmachine.png"),
  },
  {
    id: 7,
    name: "chest fly machine",
    title: "Chest Fly Machine",
    image: require("../assets/ferioLabs/chestfly.png"),
  },
  {
    id: 8,
    name: "arm extension machine",
    title: "Arm Extension Machine",
    image: require("../assets/ferioLabs/armextension.png"),
  },
  {
    id: 9,
    name: "chair",
    title: "Chair",
    image: require("../assets/ferioLabs/chair.png"),
  },
  {
    id: 10,
    name: "pull up bar",
    title: "Pull Up Bar",
    image: require("../assets/ferioLabs/pullupbar.png"),
  },
  {
    id: 11,
    name: "leg press machine",
    title: "Leg Press Machine",
    image: require("../assets/ferioLabs/legpress.png"),
  },
  {
    id: 12,
    name: "bench press machine",
    title: "Bench Press Machine",
    image: require("../assets/ferioLabs/legpress.png"),
  },
  {
    id: 13,
    name: "cabel weights",
    title: "Cable Weights",
    image: require("../assets/ferioLabs/cabelweights.png"),
  },
  {
    id: 14,
    name: "curl bar",
    title: "Curl Bar",
    image: require("../assets/ferioLabs/curlbar.png"),
  },
  {
    id: 15,
    name: "dip machine",
    title: "Dip Machine",
    image: require("../assets/ferioLabs/dip.png"),
  },
  {
    id: 16,
    name: "incline bench",
    title: "Inclinable Bench",
    image: require("../assets/ferioLabs/inclinablebench.png"),
  },
  {
    id: 17,
    name: "rowing machine",
    title: "Rowing Machine",
    image: require("../assets/ferioLabs/rowingmachine.png"),
  },
  {
    id: 18,
    name: "step platform",
    title: "Step Platform",
    image: require("../assets/ferioLabs/stepplatform.png"),
  },
  {
    id: 19,
    name: "ab wheel",
    title: "Ab Wheel",
    image: require("../assets/ferioLabs/abwheel.png"),
  },
  {
    id: 20,
    name: "yoga mat",
    title: "Yoga Mat",
    image: require("../assets/ferioLabs/yogamat.png"),
  },
  {
    id: 21,
    name: "treadmill",
    title: "Treadmill",
    image: require("../assets/ferioLabs/Treadmill.png"),
  },
  {
    id: 22,
    name: "elliptical trainer",
    title: "Elliptical Trainer",
    image: require("../assets/ferioLabs/ellipticaltrainer.png"),
  }
];
